### ISSUE TITLE
Xomni landing page

### ISSUE THREAD

**Issue by oksushi** [the-working-party/mtek#1]
Task here is to build a new landing page (xomni.com.au) which will outline the benefits of using the Xomni platform (the main parent site is http://www.xomni.com/).

Refer to Omni retail.docx for content

**Comment by oksushi** [comment]
@geoffirvine Client has come back with feedback. He wants to go with monochrome icons that he has taken from The Noun Project. These might sit on flat coloured backgrounds for each 'area'.

He also wants to do the following:

o   Bi-line at top missing
o   Swap images for graphics
o   The text boxes below each image are different sizes – some have more white, looks a bit ratty

Not sure about all this — thoughts?
 

[xomni images2.docx | uploaded via ZenHub](https://files.zenhub.io/555c1b3a6777ff675d23fb5c)

**Comment by geoffirvine** [comment]
Hi @oksushi 

Is the byline he's referring to 'experience omni-channel' which is part of the logo on the microsite home page? Is it possible to get full versions of the logo in pos and rev? The ones I've got came from the interweb, and they're not great.

Once I swap images for icons the different sized text boxes might not look so contained. But it's content, you'll always get some variation...

The noun project tend to want a small payment for the icons or an attribution. I can download them and put them in the design for now anyway.

Do you want me to go ahead with this once I've got a bit more of Sphere done?

**Comment by oksushi** [comment]
Hi — about the byline — yes I think that’s what is meant.

I’ll pay for the icons, I’ve asked him to send me the URLs. Until then we can use the unlicensed ones for development with attribution.

Yes please proceed with this. There is some feedback on the other chunk too that i haven’t yet uploaded ;)
