### ISSUE TITLE
Chainformation new links required

### ISSUE THREAD

**Issue by oksushi** [the-working-party/mtek#10]
See this 'mud map' - we need to add links for Tour and Stories, and have a secondary page for About (no content yet)
![image](https://cloud.githubusercontent.com/assets/466722/7904481/36217ea0-0840-11e5-85c4-c093e253ec85.png)

**Comment by geoffirvine** [comment]
Hi @oksushi 
I've incorporated the Chainformation landing page into the mocaltek.com microsite (links from the home page). I was wondering if this page should have an about page in the same way that I've just done for Xomni?

I also updated the mocaltek.com microsite to allow the extra menu items.
