### ISSUE TITLE
Mocal Technologies Home Page Changes

### ISSUE THREAD

**Issue by oksushi** [the-working-party/mtek#12]
**Partners**
* [ ] Lift the information from the mocal site and reposition on mocal technologies
* [ ] Add a Partners menu item on all pages linking to this Partners page

**Contact Us**
* [ ] Lift from Mocal and add a request on which product are you interested in – mocal / Xomni / Chainformation
* [ ] Add a Contact Us menu item on all pages linking here

**Check links**
* [ ] The partners and contact buttons work at the top right of home page, but not on bottom left

**Images**
* [ ] Replace home page images with 2 supplied

**Call to Action Text**
* [ ] Will to supply

**Footer**
* [ ] Change copyright tp Copyright © 2015 Bucanero Investments Pty Ltd.

**Comment by oksushi** [comment]
Images for Chainformation and Xomni
![chainformation homepage](https://cloud.githubusercontent.com/assets/466722/8124028/ccfe3716-1117-11e5-8964-ff08a1d6a143.png)
![xomni homepage](https://cloud.githubusercontent.com/assets/466722/8124029/ccff82ce-1117-11e5-8f89-7e7ca0ebdb70.png)

**Comment by geoffirvine** [comment]
Hi @oksushi 

Just sent you a zip of these updates.
