### ISSUE TITLE
XOMNI changes

### ISSUE THREAD

**Issue by oksushi** [the-working-party/mtek#13]
* [x] The radio buttons bottom left are not linked, and no buttons are available top right.  
* [x] Change About XOMNI text to supplied document
* [x] Add the pdf brochure as a download item to the ABOUT page
* [x] Change copyright to Copyright © 2015 Bucanero Investments Pty Ltd.

**Comment by oksushi** [comment]
About XOMNI

Xomni incorporates retail-specific functionality that makes for the easy building of visually exciting assisted selling, concierge, and self-service applications.

Xomni – a company whose name stands for ‘Experience Omni-channel’ – is achieving its vision through a cloud-based omni-channel customer experience and enablement platform. 

Today it is critical for retailers to bridge the gap between digital and their bricks-and-mortar stores, so that customers maintain historic loyalties whilst enjoying the capabilities of the 21st century.  What the store will do for the on-line channel, and vice versa, is to create a sense of continuity in retailing.  When these channels are harmonised, it is possible to maximise a return on investment and provide continuing satisfaction to the customer.

The company caters for creative interactive agencies to leverage the Xomni Cloud to gain access to retailers’ existing systems, add new data sources, orchestrate the data and leverage a consistent API interface to enhancing applications. 

Xomni is the next generation of in-store technologies.

**Comment by oksushi** [comment]
PDF brochure

[XOMNI Cloud 2015-1.pdf | uploaded via ZenHub](https://files.zenhub.io/557a6e81f2e14dda72536382)

[XOMNI Cloud 2015-1.pdf | uploaded via ZenHub](https://files.zenhub.io/557a6ea8f2e14dda72536383)

**Comment by geoffirvine** [comment]
Hi @oksushi 

I've just sent you a compiled version of this page.

Please note I haven't added the top row of navigation since that would be pointing to another site. The same links in the footer will need to be updated to match whatever the final domain ends up being.

Let me know if there are any problems.

Cheers

Geoff
