### ISSUE TITLE
Pull new contact page for mocaltek.com and deploy

### ISSUE THREAD

**Issue by oksushi** [the-working-party/mtek#16]
I’ve swapped their contact form for Wufoo — can you pull it down, check the styling, then deploy back to the host (they’re live BTW)

**Comment by geoffirvine** [comment]
Hi @oksushi 

Can you please download the HTML/CSS of the wufoo form so that we can embed directly? Or alternatively if you want to stick with the iframe can I have access to the wufoo account so that I can link to a custom theme?

Cheers

**Comment by geoffirvine** [comment]
Hi @oksushi 

As I mentioned on Slack - Pasting in the form code isn't really practical, as it redirects to https://mocal.wufoo.com/forms/m12cro8b1y633sr/#public when you submit, this includes the validation screen.

To use custom css file we need to link it to a css file stored securely (https).

So for now all I've been able to do is tweak the theme styles, and add some margin to the bottom of the container to clear it from the footer.

**Comment by oksushi** [comment]
OK that’s fine — what about deploying the site to the server?

**Comment by geoffirvine** [comment]
No problem, can you please send me the server login details?

**Comment by oksushi** [comment]
These are hosted with divshot — I thought you did the initial deployment

**Comment by geoffirvine** [comment]
Sorry, you're right. I'll find those details now

**Comment by geoffirvine** [comment]
Hi @oksushi 

Site is now deployed with the wufoo form. I also purged the cache so it should be ok.

Let me know if there are any problems.

Cheers

**Comment by oksushi** [comment]
:beer:
