### ISSUE TITLE
Replace Get App button

### ISSUE THREAD

**Issue by oksushi** [the-working-party/mtek#8]
> the xomni home page should have the following 2 tabs at the top (replacing get the app)
> 1st:	a link 'Stories' which takes the user to http://blog.xomni.com/category/stories/ - which is on the primary xomni website
> 2nd 	'Tours' will provide a directory of links to youtube clips from various events and demos etc.   Can these open in a new window? https://www.youtube.com/user/xomniretail/feed

**Comment by geoffirvine** [comment]
Hi @oksushi 

I've added these links - they will both open in a new window.

Do you think it might be better to open a new page and embed the videos?
