### ISSUE TITLE
Adjust footer

### ISSUE THREAD

**Issue by oksushi** [the-working-party/mtek#9]
> The footer should have the Mocaltech bar - home/what we do/how we do/contact
> Across the bottom of the page (above the Mocaltech banner) & about 2 buttons should read

> "Specialising in assisted selling and customer decision support"
> [stories]	[take a tour]

**Comment by geoffirvine** [comment]
Hi @oksushi 
I've added these links for visual now - they'll need to be updated once we know the final urls.
